# Generated by Django 4.0.5 on 2023-05-20 02:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('taxable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=25)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=13)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_positions', to='rebalancer.account')),
            ],
        ),
    ]
